import type { Category, Plan, Product } from '../model/schema';

export const CATEGORY_ORDER: Category[] = ['kitchen', 'laundry', 'tv', 'climate', 'living', 'furniture', 'bath', 'custom'];

export const CATEGORY_LABEL: Record<Category, string> = {
  kitchen: '주방가전',
  laundry: '세탁·건조',
  tv: 'TV',
  climate: '냉난방',
  living: '생활가전',
  furniture: '가구',
  bath: '욕실',
  custom: '사용자 정의',
};

// 삼성 제품 치수는 샘플 값이다. 계획 4에서 사용자가 준 모델 목록과 공식 사양으로 교체한다.
export const CATALOG: Product[] = [
  {
    id: 'samsung-bespoke-4door-sample',
    brand: 'samsung',
    model: 'BESPOKE 4도어 (샘플 치수)',
    name: '비스포크 냉장고 4도어',
    category: 'kitchen',
    dims: { w: 91, d: 93, h: 185 },
    variants: [
      { id: 'satin-white', label: '새틴 화이트', colors: { panel: '#e9e6df', body: '#c9c9c9' } },
      { id: 'glam-navy', label: '글램 네이비', colors: { panel: '#2b3446', body: '#c9c9c9' } },
    ],
    builder: 'fridge',
    builderParams: { split: '4door', topRatio: 0.58 },
    clearances: [
      { kind: 'swing', hinge: 'left', radius: 45 },
      { kind: 'swing', hinge: 'right', radius: 45 },
    ],
    power: { watts: 300, dedicatedCircuit: false },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'samsung-grande-washer-sample',
    brand: 'samsung',
    model: '그랑데 세탁기 (샘플 치수)',
    name: '그랑데 드럼세탁기',
    category: 'laundry',
    dims: { w: 70, d: 85, h: 110 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#eeeeee', door: '#3a404a' } }],
    builder: 'front-loader',
    clearances: [{ kind: 'front', depth: 60 }],
    power: { watts: 2000, dedicatedCircuit: true },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'samsung-tv-75-sample',
    brand: 'samsung',
    model: '75인치 TV (샘플 치수)',
    name: '75인치 벽걸이 TV',
    category: 'tv',
    dims: { w: 167, d: 3, h: 96 },
    variants: [{ id: 'black', label: '블랙', colors: { frame: '#1d1d1f', screen: '#0b0c10' } }],
    builder: 'tv',
    builderParams: { mountHeight: 90 },
    clearances: [],
    power: { watts: 250, dedicatedCircuit: false },
    builtIn: false,
    mount: 'wall',
  },
  {
    id: 'sofa-3seat',
    brand: 'generic',
    model: '',
    name: '3인 소파',
    category: 'furniture',
    dims: { w: 210, d: 90, h: 80 },
    variants: [{ id: 'gray', label: '그레이', colors: { fabric: '#8a8f98' } }],
    builder: 'sofa',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'bed-queen',
    brand: 'generic',
    model: '',
    name: '퀸 침대',
    category: 'furniture',
    dims: { w: 165, d: 215, h: 100 },
    variants: [{ id: 'oak', label: '오크', colors: { frame: '#b08a62', mattress: '#f4f1ea' } }],
    builder: 'bed',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'table-dining-4',
    brand: 'generic',
    model: '',
    name: '4인 식탁',
    category: 'furniture',
    dims: { w: 140, d: 80, h: 74 },
    variants: [{ id: 'oak', label: '오크', colors: { wood: '#b08a62' } }],
    builder: 'table',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  // 아래 치수는 일반값(§20.3). 삼성 모델 목록을 받으면 adding-catalog-product 절차로 교체한다
  {
    id: 'samsung-kimchi-4door-sample',
    brand: '삼성',
    model: '김치플러스 4도어 (샘플 치수)',
    name: '김치냉장고 4도어',
    category: 'kitchen',
    dims: { w: 92, d: 80, h: 185 },
    variants: [{ id: 'white', label: '화이트', colors: { panel: '#eeece6', body: '#c9c9c9' } }],
    builder: 'fridge',
    builderParams: { split: '4door', topRatio: 0.55 },
    clearances: [
      { kind: 'swing', hinge: 'left', radius: 46 },
      { kind: 'swing', hinge: 'right', radius: 46 },
    ],
    power: { watts: 250, dedicatedCircuit: false },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'samsung-induction-sample',
    brand: '삼성',
    model: '인덕션 3구 (샘플 치수)',
    name: '인덕션 3구',
    category: 'kitchen',
    dims: { w: 60, d: 52, h: 6 },
    variants: [{ id: 'black', label: '블랙', colors: { panel: '#15171a', body: '#3a3d42' } }],
    builder: 'built-in-appliance',
    builderParams: { panel: 'top' },
    clearances: [],
    power: { watts: 7200, dedicatedCircuit: true },
    builtIn: true,
    mount: 'floor',
    elevation: 87,
  },
  {
    id: 'samsung-dishwasher-sample',
    brand: '삼성',
    model: '빌트인 식기세척기 (샘플 치수)',
    name: '빌트인 식기세척기',
    category: 'kitchen',
    dims: { w: 60, d: 57, h: 82 },
    variants: [{ id: 'white', label: '화이트', colors: { panel: '#e9e6df', body: '#3a3d42' } }],
    builder: 'built-in-appliance',
    builderParams: { panel: 'door' },
    clearances: [{ kind: 'front', depth: 60 }],
    power: { watts: 2000, dedicatedCircuit: true },
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'samsung-oven-sample',
    brand: '삼성',
    model: '빌트인 오븐 (샘플 치수)',
    name: '빌트인 오븐',
    category: 'kitchen',
    dims: { w: 60, d: 57, h: 45 },
    variants: [{ id: 'black', label: '블랙', colors: { panel: '#2a2d31', body: '#3a3d42' } }],
    builder: 'built-in-appliance',
    builderParams: { panel: 'door' },
    clearances: [{ kind: 'front', depth: 50 }],
    power: { watts: 3000, dedicatedCircuit: true },
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'kitchen-base-240',
    brand: '일반',
    model: '',
    name: '싱크대 하부장 240',
    category: 'kitchen',
    dims: { w: 240, d: 60, h: 87 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df', counter: '#bdb6ad' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c', counter: '#e8e2d6' } },
    ],
    builder: 'cabinet-run',
    builderParams: { part: 'base', doors: 4, counter: true, sink: true },
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'kitchen-base-180',
    brand: '일반',
    model: '',
    name: '싱크대 하부장 180',
    category: 'kitchen',
    dims: { w: 180, d: 60, h: 87 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df', counter: '#bdb6ad' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c', counter: '#e8e2d6' } },
    ],
    builder: 'cabinet-run',
    builderParams: { part: 'base', doors: 3, counter: true },
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'kitchen-upper-240',
    brand: '일반',
    model: '',
    name: '상부장 240',
    category: 'kitchen',
    dims: { w: 240, d: 35, h: 70 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c' } },
    ],
    builder: 'cabinet-run',
    builderParams: { part: 'upper', doors: 4 },
    clearances: [{ kind: 'front', depth: 40 }],
    builtIn: true,
    mount: 'wall',
    elevation: 145,
  },
  {
    id: 'kitchen-corner-base-90',
    brand: '일반',
    model: '',
    name: '코너 하부장 90',
    category: 'kitchen',
    dims: { w: 90, d: 90, h: 87 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df', counter: '#bdb6ad' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c', counter: '#e8e2d6' } },
    ],
    builder: 'corner-cabinet',
    builderParams: { part: 'base', arm: 60 },
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'kitchen-corner-upper-60',
    brand: '일반',
    model: '',
    name: '코너 상부장 60',
    category: 'kitchen',
    dims: { w: 60, d: 60, h: 70 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c' } },
    ],
    builder: 'corner-cabinet',
    builderParams: { part: 'upper', arm: 35 },
    clearances: [{ kind: 'front', depth: 40 }],
    builtIn: true,
    mount: 'wall',
    elevation: 145,
  },
  {
    id: 'samsung-range-hood-sample',
    brand: '삼성',
    model: '레인지후드 (샘플 치수)',
    name: '레인지후드 60',
    category: 'kitchen',
    dims: { w: 60, d: 50, h: 40 },
    variants: [{ id: 'black', label: '블랙', colors: { body: '#2a2d31' } }],
    builder: 'box',
    clearances: [],
    power: { watts: 200, dedicatedCircuit: false },
    builtIn: true,
    mount: 'wall',
    elevation: 155,
  },
  {
    id: 'samsung-dryer-sample',
    brand: '삼성',
    model: '그랑데 건조기 (샘플 치수)',
    name: '그랑데 건조기',
    category: 'laundry',
    dims: { w: 60, d: 66, h: 85 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#eeeeee', door: '#3a404a' } }],
    builder: 'front-loader',
    clearances: [{ kind: 'front', depth: 60 }],
    power: { watts: 1800, dedicatedCircuit: true },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'samsung-stand-ac-sample',
    brand: '삼성',
    model: '무풍 스탠드 에어컨 (샘플 치수)',
    name: '스탠드 에어컨',
    category: 'climate',
    dims: { w: 38, d: 36, h: 188 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f2f2f2', vent: '#5c6066' } }],
    builder: 'stand-ac',
    clearances: [{ kind: 'front', depth: 30 }],
    power: { watts: 2200, dedicatedCircuit: true },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'samsung-wall-ac-sample',
    brand: '삼성',
    model: '벽걸이 에어컨 (샘플 치수)',
    name: '벽걸이 에어컨',
    category: 'climate',
    dims: { w: 85, d: 25, h: 30 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f4f4f4' } }],
    builder: 'box',
    clearances: [],
    power: { watts: 900, dedicatedCircuit: true },
    builtIn: false,
    mount: 'wall',
    elevation: 195,
  },
  {
    id: 'samsung-ceiling-ac-sample',
    brand: '삼성',
    model: '천장형 시스템 에어컨 (샘플 치수)',
    name: '천장형 시스템 에어컨',
    category: 'climate',
    dims: { w: 84, d: 84, h: 25 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f4f4f4', panel: '#ffffff', vent: '#6b7075' } }],
    builder: 'ceiling-ac',
    clearances: [],
    power: { watts: 2500, dedicatedCircuit: true },
    builtIn: true,
    mount: 'ceiling',
  },
  {
    id: 'samsung-air-purifier-sample',
    brand: '삼성',
    model: '공기청정기 (샘플 치수)',
    name: '공기청정기',
    category: 'living',
    dims: { w: 37, d: 37, h: 60 },
    variants: [{ id: 'gray', label: '그레이', colors: { body: '#d8d9db' } }],
    builder: 'box',
    clearances: [],
    power: { watts: 60, dedicatedCircuit: false },
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'wardrobe-builtin-240',
    brand: '일반',
    model: '',
    name: '붙박이장 240',
    category: 'furniture',
    dims: { w: 240, d: 60, h: 230 },
    variants: [
      { id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df' } },
      { id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c' } },
    ],
    builder: 'wardrobe',
    builderParams: { doors: 4 },
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'wardrobe-120',
    brand: '일반',
    model: '',
    name: '옷장 120',
    category: 'furniture',
    dims: { w: 120, d: 60, h: 200 },
    variants: [{ id: 'oak', label: '오크', colors: { body: '#b08a62', door: '#c9a06c' } }],
    builder: 'wardrobe',
    builderParams: { doors: 2 },
    clearances: [
      { kind: 'swing', hinge: 'left', radius: 60 },
      { kind: 'swing', hinge: 'right', radius: 60 },
    ],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'shoe-cabinet-120',
    brand: '일반',
    model: '',
    name: '신발장 120',
    category: 'furniture',
    dims: { w: 120, d: 40, h: 180 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#d9d3ca', door: '#efe9df' } }],
    builder: 'wardrobe',
    builderParams: { doors: 2 },
    clearances: [{ kind: 'front', depth: 40 }],
    builtIn: true,
    mount: 'floor',
  },
  {
    id: 'desk-140',
    brand: '일반',
    model: '',
    name: '책상 140',
    category: 'furniture',
    dims: { w: 140, d: 70, h: 73 },
    variants: [{ id: 'oak', label: '오크', colors: { wood: '#b08a62' } }],
    builder: 'table',
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'chair-dining',
    brand: '일반',
    model: '',
    name: '의자',
    category: 'furniture',
    dims: { w: 45, d: 50, h: 85 },
    variants: [{ id: 'oak', label: '오크', colors: { wood: '#b08a62', seat: '#d8cfc0' } }],
    builder: 'chair',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'tv-stand-180',
    brand: '일반',
    model: '',
    name: 'TV장 180',
    category: 'furniture',
    dims: { w: 180, d: 40, h: 45 },
    variants: [{ id: 'walnut', label: '월넛', colors: { body: '#7a5230', door: '#8c6240' } }],
    builder: 'cabinet-run',
    builderParams: { part: 'base', doors: 3, counter: false },
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'bed-super-single',
    brand: '일반',
    model: '',
    name: '슈퍼싱글 침대',
    category: 'furniture',
    dims: { w: 110, d: 205, h: 100 },
    variants: [{ id: 'oak', label: '오크', colors: { frame: '#b08a62', mattress: '#f4f1ea' } }],
    builder: 'bed',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'toilet-std',
    brand: '일반',
    model: '',
    name: '양변기',
    category: 'bath',
    dims: { w: 38, d: 70, h: 78 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f7f7f5' } }],
    builder: 'toilet',
    clearances: [{ kind: 'front', depth: 50 }],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'basin-std',
    brand: '일반',
    model: '',
    name: '세면대',
    category: 'bath',
    dims: { w: 55, d: 45, h: 85 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f7f7f5', cabinet: '#d9d3ca' } }],
    builder: 'basin',
    builderParams: { cabinet: true },
    clearances: [{ kind: 'front', depth: 50 }],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'shower-90',
    brand: '일반',
    model: '',
    name: '샤워부스 90',
    category: 'bath',
    dims: { w: 90, d: 90, h: 200 },
    variants: [{ id: 'clear', label: '투명', colors: { tray: '#e8e8e6', frame: '#8a8a8a' } }],
    builder: 'shower',
    clearances: [{ kind: 'front', depth: 60 }],
    builtIn: false,
    mount: 'floor',
  },
  {
    id: 'bathtub-150',
    brand: '일반',
    model: '',
    name: '욕조 150',
    category: 'bath',
    dims: { w: 150, d: 75, h: 55 },
    variants: [{ id: 'white', label: '화이트', colors: { body: '#f7f7f5' } }],
    builder: 'box',
    clearances: [],
    builtIn: false,
    mount: 'floor',
  },
];

export function findProduct(plan: Plan, productId: string): Product | undefined {
  return plan.customProducts.find((p) => p.id === productId) ?? CATALOG.find((p) => p.id === productId);
}
